services:
  - type: web
    name: salary-calculator-backend
    env: node
    plan: free
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm run start:prod
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SYNC
        value: 'true'
      - key: FRONTEND_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: UPI_ID
        sync: false
      - key: MERCHANT_NAME
        value: SalaryCalc
      - key: PAYMENT_SECRET
        sync: false
